#cloud-config
hostname: __SUBDOMAIN__

package_update: true
package_reboot_if_required: true

manage_resolv_conf: true
resolv_conf:
  nameservers:
    - "8.8.8.8"
    - "8.8.4.4"

users:
  - name: __USERNAME__
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - __SSH_PUBLIC__
    groups:
      - ubuntu
      - docker
    sudo:
      - ALL=(ALL) NOPASSWD:ALL

packages:
  - docker.io
  - docker-compose

runcmd:
  - mkdir -p /shared/config/__SUBDOMAIN__ /shared/gdrive /shared/.gcache
  - echo IPV4=$(wget http://169.254.169.254/latest/meta-data/public-ipv4 -O- -q) > /shared/config/__SUBDOMAIN__/.env
  - chown -R __USERNAME__:__USERNAME__ /shared/config /shared/gdrive /shared/.gcache
  - sudo systemctl start rc-local
write_files:
  - path: /shared/config/traefik/acme.json
    permissions: "0600"
    content: "{}"
  - path: /shared/config/traefik/traefik.log
    permissions: "0600"
    content: ""
  - path: /shared/config/__SUBDOMAIN__/docker-compose.yml
    permissions: "0755"
    content: |
      __DOCKER_COMPOSE_FILE__
  - path: /shared/config/traefik/traefik.yml
    permissions: "0755"
    content: |
      __TRAEFIK_CONFIG_FILE__
  - path: /shared/config/traefik/auth.ini
    permissions: "0755"
    content: |
      __AUTH_CONFIG_FILE__
  - path: /etc/rc.local
    permissions: "0755"
    content: |
      #!/bin/bash
      cd /shared/config/__SUBDOMAIN__
      while ! docker ps; do sleep 5; done
      docker network create __NETWORK_NAME__ || true
      docker-compose up -d
  - path: /shared/config/rclone/.rclone.conf
    permissions: "0666"
    content: |
      [gdrive]
      type = drive
      client_id = 
      client_secret = 
      scope = drive
      root_folder_id = 
      service_account_file = 
      token = __RCLONE_TOKEN__

      [gcache]
      type = cache
      remote = gdrive:
      chunk_size = 5M
      info_age = 24h
      chunk_total_size = 5G

      [gcrypt]
      type = crypt
      remote = gcache:encrypt
      filename_encryption = standard
      directory_name_encryption = true
      password = __GDRIVE_CRYPT_PASS1__
      password2 = __GDRIVE_CRYPT_PASS2__
