version: "2"
services:
  ddns4:
    image: oznu/cloudflare-ddns
    environment:
      - EMAIL=__EMAIL__
      - API_KEY=__CF_APIKEY__
      - ZONE=__DOMAIN__
      - SUBDOMAIN=*.__SUBDOMAIN__
      - PROXIED=false
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    network_mode: host
    restart: always
  ddns4sub:
    image: oznu/cloudflare-ddns
    environment:
      - EMAIL=__EMAIL__
      - API_KEY=__CF_APIKEY__
      - ZONE=__DOMAIN__
      - SUBDOMAIN=__SUBDOMAIN__
      - PROXIED=false
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    network_mode: host
    restart: always
  zerotier:
    image: spikhalskiy/zerotier
    volumes:
      - /shared/config/zerotier:/var/lib/zerotier-one
    environment:
      - NETWORK_ID=__ZEROTIER_NETWORK_ID__
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    network_mode: host
    restart: always
    privileged: true
  traefik:
    container_name: traefik
    image: traefik:v2.2
    command: -c /traefik.yml --logLevel=DEBUG
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /shared/config/traefik/traefik.yml:/traefik.yml:ro
      - /shared/config/traefik/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - ddns4
      - ddns4sub
    labels:
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    networks:
      - __NETWORK_NAME__
  auth:
    container_name: auth
    image: thomseddon/traefik-forward-auth:2
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID=__GOOGLE_CLIENT_ID__
      - PROVIDERS_GOOGLE_CLIENT_SECRET=__GOOGLE_CLIENT_SECRET__
      - SECRET=__SECRET__
      # - INSECURE_COOKIE=true
      - WHITELIST=__EMAIL__
      - COOKIE_DOMAIN=__DOMAIN__
      - AUTH_HOST=auth.__SUBDOMAIN__.__DOMAIN__
    depends_on:
      - ddns4
      - ddns4sub
    labels:
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.services.auth.loadbalancer.server.port=4181"
    networks:
      - __NETWORK_NAME__
  portainer:
    container_name: portainer
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /shared/config/portainer:/data
    restart: always
    networks:
      - __NETWORK_NAME__
  hello1:
    container_name: hello1
    image: nginxdemos/hello
    ports:
      - "10001:80"
    restart: always
    networks:
      - __NETWORK_NAME__
networks:
  __NETWORK_NAME__:
    external: true
  # rclone:
  #   image: tynor88/rclone-mount:dev
  #   container_name: rclone
  #   volumes:
  #     - /shared/config/rclone:/config
  #     - /shared/gdrive:/data:shared
  #     - /shared/.gcache:/cache
  #   environment:
  #     - RCLONE_CACHE_DB_PATH=/cache
  #     - "RCLONE_REMOTE_MOUNT=gcrypt:"
  #     - RCLONE_MOUNT_OPTIONS=-vv --allow-non-empty --fast-list
  #     - PUID=1000
  #     - PGID=1000
  #   devices:
  #     - /dev/fuse:/dev/fuse
  #   cap_add:
  #     - SYS_ADMIN
  #   security_opt:
  #     - apparmor:unconfine
  #     - apparmor:unconfined
  #   restart: always
  #   privileged: true
  # plex:
  #   image: plexinc/pms-docker
  #   container_name: plex
  #   depends_on:
  #     - rclone
  #   volumes:
  #     - /shared/config/plex:/config
  #     - /shared/gdrive/tv:/tv
  #     - /shared/gdrive/movies:/movies
  #   environment:
  #     - PLEX_UID=1000
  #     - PLEX_GID=1000
  #     - TZ=America/Sao_Paulo
  #     - PLEX_CLAIM=__PLEX_CLAIM__
  #     - ADVERTISE_IP=http://${IPV4}:32400/
  #   network_mode: host
  #   restart: always
  #   labels:
  #     - "traefik.port=32400"
