entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: default
      middlewares:
        - traefik-forward-auth

certificatesResolvers:
  default:
    acme:
      email: __ACME_EMAIL__
      storage: acme.json
      httpChallenge:
        entryPoint: web
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory

providers:
  providersThrottleDuration: 2s
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: true
    useBindPortIP: true
    network: __NETWORK_NAME__
    swarmModeRefreshSeconds: 15s
    defaultRule: 'Host(`{{ regexReplaceAll "(.*)-[^-]+$" .Name "${1}" }}.__SUBDOMAIN__.__DOMAIN__`)'

api:
  insecure: true
  dashboard: true
  debug: true

ping: {}

log:
  level: DEBUG
